### ISSUE TITLE
Couple of issues trying to Build or Make

### ISSUE THREAD

**Issue by samtempledev** [scherererer/SonarPhony#3]
/home/sam/Git/SonarPhony/include/sonarphony/pingMsg.H:30: error: implicitly-declared ‘sonarphony::sonarMsg_t& sonarphony::sonarMsg_t::operator=(const sonarphony::sonarMsg_t&)’ is deprecated [-Werror=deprecated-copy]
   30 | class pingMsg_t : public sonarMsg_t
      |       ^~~~~~~~~
      
/home/sam/Git/SonarPhony/apps/sonarphony/columnPulser.C:99: error: implicitly-declared ‘sonarphony::pingMsg_t& sonarphony::pingMsg_t::operator=(const sonarphony::pingMsg_t&)’ is deprecated [-Werror=deprecated-copy]
   99 |  m_lastMsg = ping_;
      |              ^~~~~

**Comment by Hommus** [comment]
@samtempledev A similar problem was discussed in another issue, check if this solution works: https://github.com/scherererer/SonarPhony/issues/1#issuecomment-621130892

**Comment by samtempledev** [comment]
@Paulie-P I dont believe these are the same issue, that issue was around flags in MACOS and LINUX, this is actually an issue in the code with depricated methods
