### ISSUE TITLE
Daemon + Ideas

### ISSUE THREAD

**Issue by samtempledev** [scherererer/SonarPhony#4]
Can anyone help me with running the daemon, i would like to run this on boot of a raspberry pi that is inside my rc boat and output the data to a txt file.

Ultimately I would like to add a USB GPS to the raspberry pi and extend the daemon code to add the GPS coordinates to the nmea data so I can use this depth and gps data to create bathymetric maps in reefmaster.

**Comment by samtempledev** [comment]
I can get the daemon to run in terminal but not sure what to use for -c [config file]

**Comment by Hommus** [comment]
@samtempledev try ./sonarphonyd -c daemon.C

**Comment by scherererer** [comment]
Fixed.. I had the intention of allowing a configuration file capability but never did it. So I just removed the required (but unnecessary) option
